#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rsshub"
name = "RSSHub"
description.en = "Extensible RSS feed aggregator"
description.fr = "Agrégateur de flux RSS extensible"

version = "2023.11.03~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://docs.rsshub.app/"
admindoc = "https://docs.rsshub.app/install/"
code = "https://github.com/DIYgod/RSSHub"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/DIYgod/RSSHub/archive/e8212ff05ef1f4a10c4ce9ca1db27b12702e1886.tar.gz"
        sha256 = "e48fbe767d677db153f80db5c84bc91ca4748e6997f645e49401b3e40aea56f2"
        autoupdate.upstream = "https://github.com/DIYgod/RSSHub"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 1200

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
