#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rsshub"
name = "RSSHub"
description.en = "Extensible RSS feed aggregator"
description.fr = "Agrégateur de flux RSS extensible"

version = "2023.12.10~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://docs.rsshub.app/"
admindoc = "https://docs.rsshub.app/install/"
code = "https://github.com/DIYgod/RSSHub"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/DIYgod/RSSHub/archive/51a0608a1e730b752b3b1cd75f8af72cbfa4984b.tar.gz"
        sha256 = "55b33d080f0f497eea896d7d2d9cef01f7f810608ecc6798ae64d879ecb0e3af"
        autoupdate.upstream = "https://github.com/DIYgod/RSSHub"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 1200

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
